name: cooler_binder
channels:
  - bioconda
dependencies:
- python=3.7
- numpy
- cython
- ipython
- h5py
- pairix
- pip
- pip:
  - cooler
  - dask[array,dataframe]
  - matplotlib
  - pandas
  - seaborn
